services:
  - type: web
    name: bibliothek-kindle-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SENDGRID_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: ALLOWED_ORIGIN
        sync: false
      - key: NODE_ENV
        value: production
